steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'list']

## Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute scp --recurse src/ swos@instance-1:/home/swos --zone europe-west4-a
  id: 'deploy'
