steps:
## Deploy API docs
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute scp --recurse instance-1:/home/swos . --zone europe-west4-a
  id: 'deploy'
