steps:
## Deploy API docs
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute --zone "europe-west4-a" scp --recurse instance-1:/home/swos .
  id: 'deploy'
