steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'list']

## Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute project-info add-metadata --metadata-from-file ssh-keys=/builder/home/.ssh/
    gcloud compute scp --recurse swos@instance-1:/home/swos src/ --zone europe-west4-a
  id: 'deploy'
